<div class="has-nav">

    <?php require_once('global/nav-docs.php'); ?>

    <div>

        <section>

            <p>Wayfinder is setup to work with MySQL out of the box. To get started, just ammend the configuration in the <code>app/conf/db.php</code> file so that it points to your database.</p>

            <p>You will need to load the DB from the libraries folder and into your Class, like so:</p>

            <code><pre>class Items extends Wayfinder {

    private $_db;

    public function __construct() {
        $this->load('libraries', 'db');
        $this->_db = new Db();
    }

}</pre></code>

            <p>Once your database connection has been established, you can start working with the helper methods supplied.</p>

            <h2 id="query"><a href="#query" aria-label="query()">¶</a> query()</h2>

            <p>The <code>query()</code> method is a wrapper for running any type of query.</p>

            <code><pre>public function addItem($name) {
    $sql = "SELECT * FROM myTable LIMIT 10";
    $results = $this->_db->query($sql);
}</pre></code>

            <h2 id="escape"><a href="#escape" aria-label="escape()">¶</a> escape()</h2>

            <p><code>escape()</code> is a wrapper for PHP's own <code>mysqli_real_escape_string</code> method. You should escape your own inputs, especially when the content is user generated. You can call it when constructing your queries like so:</p>

            <code><pre>public function addItem($name) {
    $sql = "INSERT INTO myTable (column1, column2)
            VALUES ('myFirstVal', ".$this->_db->escape($_POST['username']).")";
    $this->_db->query($sql);
    return $this->_db->lastInsert();
}</pre></code>

            <h2 id="lastinsertid"><a href="#lastinsertid" aria-label="lastInsertId()">¶</a> lastInsertId()</h2>

            <p>After executing a query, you can fetch the ID generated by the last insert.</p>

            <code><pre>public function addItem($name) {
    // generate query
    // $sql = "INSERT ...";
    $this->_db->query($sql);
    return $this->_db->lastInsert();
}</pre></code>

            <h2 id="error"><a href="#error" aria-label="error()">¶</a> error()</h2>

            <p>Use this method to return any errors related to queries that fail to execute.</p>

        </section>

    </div>

</div>
