<div class="has-nav">

    <?php require_once('global/nav-docs.php'); ?>

    <div>

        <section>

            <p>Wayfinder is setup to work with MySQL out of the box. To get started, just ammend the configuration in the <code>app/conf/db.php</code> file so that it points to your database.</p>

            <p>You will need to load the DB from the libraries folder and into your Class, like so:</p>

            <code><pre>class Items extends Wayfinder {

    private $_db;

    public function __construct() {
        $this->load('libraries', 'db');
        $this->_db = new Db();
    }

}</pre></code>

            <p>Once your database connection has been established, you can start working with the helper functions supplied.</p>

            <h2>query()</h2>

            <h4>Introduced in v0.2</h4>

            <p>The <code>query()</code> method is a wrapper for running any type of query.</p>

            <h2>lastInsertId()</h2>

            <p>After executing a query, you can fetch the ID generated by the last insert.</p>

            <code><pre>public function addItem($name) {
    // generate query
    // $sql = "INSERT ...";
    $this->_db->query($sql);
    return $this->_db->lastInsert();
}</pre></code>

            <h2>error()</h2>

            <p>Use this method to return any errors related to queries that fail to execute.</p>

        </section>

    </div>

</div>
