<div class="has-nav">

    <?php require_once('global/nav-docs.php'); ?>

    <div>

        <section>

            <p>Most errors in Wayfinder are treated as though something is missing (404) or as a bad request (400). You can always throw your own errors with more appropriate error codes if required.</p>

            <code><pre>$this->_error = new Errors();
$this->_error->index(410);</pre></code>

            <p>You can also overwrite the titles and/or the messages generated by Wayfinder. An error code is required, but the <code>$title</code> and <code>$message</code> parameters are optional and should be specified in that order. If you only want to set the message and not a title, then you can pass the title as <code>false</code>.</p>

            <code><pre>$this->_error = new Errors();
// error = 410, title = Gone
$this->_error->index(410, 'Gone');</pre></code>

            <code><pre>$this->_error = new Errors();
// error = 410, message = find it here...
$this->_error->index(410, false, 'find it here...');</pre></code>

        </section>

        <section>

            <h2>Supported error codes</h2>

            <p>You can pass your own error codes and error messages, but the following error codes are supported out of the box:</p>

            <ul>
                <li><code>400</code> Bad Request</li>
                <li><code>401</code> Unauthorized</li>
                <li><code>403</code> Forbidden</li>
                <li><code>501</code> Not Implemented</li>
                <li><code>503</code> Service Unavailable</li>
                <li><code>404</code> Not Found</li>
            </ul>

        </section>

    </div>

</div>
