name: CI

on: [push]

jobs:
  code-sniff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 7.4.3
          standard: phpcs.xml

  phpunit:
    needs: code-sniff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PHPUnit
        env:
          TEST_NAME: GitHubActions
        with:
          php_version: 7.4.3
          version: 9.6
          configuration: tests/phpunit.xml
          args: --coverage-text
